version: '3.8'

services:
  db:
    image: postgres:15
    container_name: brs_postgres
    environment:
      POSTGRES_DB: brs_dev
      POSTGRES_USER: brs_user
      POSTGRES_PASSWORD: brs_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brs_user -d brs_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Optional: Redis for caching and sessions (future use)
  redis:
    image: redis:7-alpine
    container_name: brs_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: brs_network
