spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/brs_dev
    username: brs_user
    password: dev_password
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    clean-disabled: false
    clean-on-validation-error: true

logging:
  level:
    com.talentica.brs: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
