apiVersion: v1
kind: Secret
metadata:
  name: brs-secrets
  namespace: brs-production
type: Opaque
data:
  # These values will be populated by AWS Secrets Manager
  # Base64 encoded placeholder values (replace with actual values)
  database-url: cG9zdGdyZXNxbDovL2Jyc191c2VyOmJyc19wYXNzd29yZEBsb2NhbGhvc3Q6NTQzMi9icnNfZGV2
  jwt-secret: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9uLXRoaXMtc2hvdWxkLWJlLWEtbG9uZy1yYW5kb20tc3RyaW5n
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: brs-config
  namespace: brs-production
data:
  ENVIRONMENT: "production"
  AWS_REGION: "us-east-1"
  AWS_SECRETS_MANAGER: "true"
  LOG_LEVEL: "INFO"
  ENABLE_METRICS: "true"


