"""Add additional performance indexes

Revision ID: 0dc08447ccf6
Revises: e200c4daa502
Create Date: 2025-09-02 18:57:55.254016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc08447ccf6'
down_revision = 'e200c4daa502'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Additional performance indexes as per Technical PRD
    op.create_index('idx_books_average_rating', 'books', ['average_rating'], unique=False, postgresql_using='btree', postgresql_ops={'average_rating': 'DESC'})
    op.create_index('idx_book_genres_book', 'book_genres', ['book_id'], unique=False)
    op.create_index('idx_book_genres_genre', 'book_genres', ['genre_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop additional performance indexes
    op.drop_index('idx_book_genres_genre', table_name='book_genres')
    op.drop_index('idx_book_genres_book', table_name='book_genres')
    op.drop_index('idx_books_average_rating', table_name='books')
    # ### end Alembic commands ###
