"""add_unique_constraint_user_book_review

Revision ID: e3b3dd9b6347
Revises: 4145f14198c3
Create Date: 2025-09-02 20:14:21.628082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b3dd9b6347'
down_revision = '4145f14198c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_book_genres_book'), table_name='book_genres')
    op.drop_index(op.f('idx_book_genres_genre'), table_name='book_genres')
    op.drop_index(op.f('idx_book_author_lower'), table_name='books')
    op.drop_index(op.f('idx_book_created_at'), table_name='books')
    op.drop_index(op.f('idx_book_rating_date'), table_name='books')
    op.drop_index(op.f('idx_book_search_title_author'), table_name='books')
    op.drop_index(op.f('idx_book_title_lower'), table_name='books')
    op.drop_index(op.f('idx_books_average_rating'), table_name='books')
    op.create_unique_constraint('unique_user_book_review', 'reviews', ['user_id', 'book_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_book_review', 'reviews', type_='unique')
    op.create_index(op.f('idx_books_average_rating'), 'books', [sa.literal_column('average_rating DESC')], unique=False)
    op.create_index(op.f('idx_book_title_lower'), 'books', [sa.literal_column('lower(title::text)')], unique=False)
    op.create_index(op.f('idx_book_search_title_author'), 'books', ['title', 'author'], unique=False)
    op.create_index(op.f('idx_book_rating_date'), 'books', ['average_rating', 'publication_date'], unique=False)
    op.create_index(op.f('idx_book_created_at'), 'books', ['created_at'], unique=False)
    op.create_index(op.f('idx_book_author_lower'), 'books', [sa.literal_column('lower(author::text)')], unique=False)
    op.create_index(op.f('idx_book_genres_genre'), 'book_genres', ['genre_id'], unique=False)
    op.create_index(op.f('idx_book_genres_book'), 'book_genres', ['book_id'], unique=False)
    # ### end Alembic commands ###
